/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.util.List;

public class Main {
    
	public static void main (String [] args) {
    }
    
    /**
     * Inserta un objeto de tipo User profile en la lista
     * @param lista
     * @param datos formato "nick>dd/MM/yyyy>3.2
     */
    public static void alta (List<UserProfile> lista, String datos) {
    }
    
    /**
     * Elimina un objeto de la lista
     * @param lista
     * @param elemento a Eliminar
     * @return true si se elimino, false en caso contrario
     */
    public static boolean baja (List<UserProfile> lista, UserProfile elemento) {
    	return false;
    }
    
    /**
     * Guarda los datos a un fichero
     * Pregunta al usuario el nombre del fichero y lo recupera
     * usando el metodo nextLine() de Scanner
     * Por cada elemento de la lista escribe una linea en el fichero
     * con el mismo formato que utiliza el alta de lista
     * @param lista
     */
    public static void salvarDatos(List<UserProfile> lista) {
    }
    
    /**
     * Fichero que lee de disco un fichero con datos para cargarlo en
     * la lista que se pasa como parametro
     * Pregunta al usuario el nombre del fichero y lo recupera
     * usando el metodo nextLine() de Scanner
     * Por cada elemento de la lista hay una linea en el fichero
     * con el mismo formato que utiliza el alta de lista
     * @param lista
     */
    public static void cargarDatos(List<UserProfile> lista) {
    }
    
    /**
     * Metodo que realiza el ordenamiento natural de una lista que se pasa
     * como parametro
     * @param lista
     */
    public static void ordena(List<UserProfile> lista) {
    }
    
    /**
     * Metodo que realiza el ordenamiento por Rating de una lista que se pasa
     * como parametro
     * @param lista
     */
    public static void ordenaRating(List<UserProfile> lista) {
    }
    
    
    
    
    
}
